#
## Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: CloudPool浊池
description: CloudPool浊池是由年轻人管理的博客
summary: Since 2017
github_username: cloudpool2017
gitlab_username: CloudPool
language: zh-Hans
timezone: Asia/Shanghai
logo: /images/logo.svg
favicon: /images/cloudpool-favicon.ico
keyword: 浊池, CloudPool, CloudPool浊池

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://zhuochi.org
root: /
permalink: :title/
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy: 
- type: git
  repo: git@github.com:StarunneR/CloudPool.git
  branch: gh-page

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archive
category_dir: categories
mag_dir: cloudpool
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: # Open external links in new tab
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
marked: # hexo-renderer-marked introduced a new option
  prependRoot: true
  postAsset: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 15
  order_by: -date
  
# Category & Tag
default_category: 浊池
category_map:
  浊池: main
  浊诗: poem
  浊shi: sh*t 
  浊故事: story 
  浊技术: tec
  浊喳喳: zhazha
  浊物理: phys
  浊行: travel
  浊安利: anli
  浊拍: shooting 
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 20
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: vexo

about: 
  banner: /images/about.jpg
  avatar: /images/logo.png
  cloudpool: /images/cloudpool.png 
  sitedescription: CloudPool浊池是由一群年轻人管理的博客。
                   如果你也有兴趣加入我们或者给我们提意见，欢迎联系我们<br/>
                   邮箱：<a href=mailto:cloudpool2017@outlook.com>cloudpool2017@outlook.com</a><br/>
                   我的QQ：1783074382
  
member:
  total: 7
  m1: StʌrunneR
  descriptionm1: 站长
  contactm1: QQ 1783074382<br/>邮箱 cloudpool2017@outlook.com
  m2: Dark.∞
  descriptionm2: 这个人什么都不想写，很懒
  contactm2: QQ 1287008710
  m3: Rev.
  descriptionm3: 优雅
  contactm3:
  m4: 寻影无人的旋律
  descriptionm4: 
  contactm4: 
  m5: Gunsbrook
  descriptionm5:  
  contactm5: QQ 1291183647<br/>1291183647@qq.com<br/>Gunsbrook Co.,Ltd.<br/>
  m6: 缀理
  descriptionm6:
  contactm6: 
  m7: Ghost
  descriptionm7: 
  contactm7: QQ 970246988

algolia:
  applicationID: 'HT8BNHADA7'
  apiKey: 'ab0da26917fd9c0cd35e59681628c169'
  adminApiKey: "258edd55b609bc85dc3c236e0b344d9f"
  indexName: 'cloudpool'