excerpt_link: 阅读全文

menu:
  主页: /
  分类: categories/
  标签: tags/
  归档: archive/
  网刊: mag/
  一言: one/
  网盘: //pan.zhuochi.org/CloudShare/
  ( ^ω^): //<emoji>
# LOFTER: https://cloudpool.lofter.com
# 关于: /about/

footer: <a href="https://zhuochi.org" target="_blank">zhuochi.org</a> || <a href="https://voiiu.com" target="_blank">voiiu.com</a><br/>
    本站为基于<a href="https://hexo.io" target="_blank">Hexo</a>的静态博客，<span id="busuanzi_container_site_pv">总访问量 <span id="busuanzi_value_site_pv"></span> 次</span><!--，来自 <span id="busuanzi_value_site_uv"></span> 个 IP--><br/>
    主题源自 <a href="https://github.com/yanm1ng/hexo-theme-vexo">Vexo</a> by yanm1ng，感谢 <a href="https://github.com/MoePlayer/APlayer">APlayer</a> by DIYgod，感谢 <a href="https://github.com/stevenjoezhang/live2d-widget">Live2D Widget</a> by stevenjoezhang & <a href="https://github.com/xiazeyu/live2d-widget-models">live2d-widget-models</a> by xiazeyu

post:
  comment: true
  qrcode: true
  reward: false
  ad: true

# titleHider Meaasge
hider:
  hidden: (つェ⊂) 看不见我看不见我~
  return: ᕕ( ᐛ )ᕗ 欢迎回来！
  timeout: 2000 ## ms

# Comment
comment:
  waline:
    serverURL: walinecf.zhuochi.org
    appId: M2JD6yGQhefhH2O0aSjFfclc-MdYXbMMI
    appKey: arEPHdbMnKwMjQgiWsLgw34N
    requiredMeta: ''
    placeholder: '说、什么8 \n\n可使用QQ邮箱获取QQ头像，或在gravatar.com注册后使用邮箱绑定头像 \n\n支持Markdown语法：*斜体*, **粗体**, \# - ###### 1-6级标题, *** 或 --- = 水平分割线, ~~删除线~~, > 引用内容, `代码块`, 1. 序号列表, * 无序列表, ^上角标^, ~下角标~, <br> = 空行, [链接文字](链接地址), ![图片名称](图片地址.png), '
    meta: ['nick','mail']
    counting: true

social:
  email: cloudpool2017@gmail.com
  sina: https://service.weibo.com/share/share.php?
  douban: https://www.douban.com/recommend/?
  tieba: http://tieba.baidu.com/f/commit/share/openShareApi?
  qzone: https://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?
  qq: https://connect.qq.com/widget/shareqq/index.html?

highlight:
  tomorrow

# catalog
catalog: true

baidu_id: 

# MathJax Support
mathjax:
  enable: false
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML

# Local Search Support
local_search:
  enable: true
  ##preload: true
  root: ''
  trigger: auto
  unescape: false
  placeholder: Anything...  今天想看什么w
  top_n_per_article: 1


# hexo-generator-search
search:
  path: search.xml
  field: post
  format: html
  ##limit: 10000
  content: true
  template: ./search.xml
  ##format: html
  ##format: striptags

# hexo-lazyload-image
lazyload:
  enable: true
  onlypost: true # optional
  loadingImg: images/loading-small.gif # optional eg /images/loading.gif
  isSPA: false # optional
  preloadRatio: 1 # optional, default is 1

live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: true
  debug: false
  model:
    use: live2d-widget-model-hijiki #这里改为你模型的名字
  display:
    position: right  #left放左，right放右
    width: 150
    height: 300
  mobile:
    show: true
  react:
    opacity: 0.7

aplayer:
  #host0: https://hkstcp.s3.ap-east-1.amazonaws.com
  host: https://cps3storage.s3.ap-southeast-1.amazonaws.com
  host1: https://cp-bitiful1.s3.bitiful.net